export const data = {
  flashcards: [
    { vocabulary: "das Ahornblatt", emojiCode: "1f341" },
    { vocabulary: "die Palme", emojiCode: "1f334" },
    { vocabulary: "das Blatt", emojiCode: "1f343" },
    { vocabulary: "der Regenbogen", emojiCode: "1f308" },
    { vocabulary: "der Pilz", emojiCode: "1f344" },
    { vocabulary: "die Welle", emojiCode: "1f30a" },
    { vocabulary: "das Wasser", emojiCode: "1f4a7" },
    { vocabulary: "der Kaktus", emojiCode: "1f335" },
    { vocabulary: "das Gewürzkraut", emojiCode: "1f33f" },
    { vocabulary: "die Schneeflocke", emojiCode: "2744" },
    { vocabulary: "der Nadelbaum", emojiCode: "1f332" },
    { vocabulary: "das Laub ", emojiCode: "1f342" },
    { vocabulary: "das Feuer", emojiCode: "1f525" },
    { vocabulary: "der Vulkan", emojiCode: "1f30b" },
    { vocabulary: "die Kirschblüte", emojiCode: "1f338" },
    { vocabulary: "die Blume", emojiCode: "1f33c" },
    { vocabulary: "die Galaxie", emojiCode: "1f30c" },
    { vocabulary: "das Kleeblatt", emojiCode: "1f340" },
    { vocabulary: "der Komet", emojiCode: "2604" },
    { vocabulary: "die Erde", emojiCode: "1f30d" },
    { vocabulary: "der Baum", emojiCode: "1f333" },
    { vocabulary: "die Tulpe", emojiCode: "1f337" },
    { vocabulary: "die Rose", emojiCode: "1f339" },
    { vocabulary: "der Berg", emojiCode: "1f5fb" },
    { vocabulary: "die Sonnenblume", emojiCode: "1f33b" },
    { vocabulary: "der Hibiskus", emojiCode: "1f33a" },
    { vocabulary: "der Setzling", emojiCode: "1f331" },
    { vocabulary: "der Stern", emojiCode: "1f31f" },
    { vocabulary: "die Sonne", emojiCode: "1f31e" },
    { vocabulary: "der Mond", emojiCode: "1f31d" },
    { vocabulary: "die Feldfrucht", emojiCode: "1f33e" },
  ],
  language: "German",
  category: "Nature",
  languageEmojiCode: "1f1e9-1f1ea",
  categoryEmojicode: "1f333",
};
